/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View, StyleSheet } from "react-native";
import AlphabetButtons from "./AlphabetButtons";
import AddressCards from "./AddressCards";

type AddressBookProps = {
  // Add any props if needed
};

const AddressBook: React.FC<AddressBookProps> = () => {
  return (
    <View style={styles.container}>
      <AlphabetButtons />
      <AddressCards />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    fontFamily: "Arial, sans-serif",
    maxWidth: 1200,
    margin: "0 auto",
    padding: "0 15px",
  },
});

export default AddressBook;
