/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View, StyleSheet } from "react-native";
import AddressCard from "./AddressCard";

const addressData = [
  {
    name: "Tanaka Taro",
    address: "123-4567 Tokyo-to Shibuya-ku",
    phone: "03-1234-5678",
  },
  {
    name: "Sato Hanako",
    address: "987-6543 Osaka-fu Kita-ku",
    phone: "06-8765-4321",
  },
  {
    name: "Yamada Ichiro",
    address: "112-2334 Kyoto-fu Nakagyo-ku",
    phone: "075-5555-4444",
  },
];

const AddressCards: React.FC = () => {
  return (
    <View style={styles.cardContainer}>
      {addressData.map((data, index) => (
        <AddressCard key={index} {...data} />
      ))}
    </View>
  );
};

const styles = StyleSheet.create({
  cardContainer: {
    columnGap: 15,
    display: "flex",
    flexDirection: "column",
    gap: 15,
    gridColumnGap: 15,
    gridGap: 15,
    gridRowGap: 15,
    rowGap: 15,
  },
});

export default AddressCards;
