/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View, StyleSheet } from "react-native";
import AlphabetButton from "./AlphabetButton";

const alphabetButtons = [
  "あ",
  "か",
  "さ",
  "た",
  "な",
  "は",
  "ま",
  "や",
  "ら",
  "わ",
  "番地",
  "南",
  "中",
  "北",
  "東",
  "泊",
];

const AlphabetButtons: React.FC = () => {
  return (
    <View style={styles.buttonContainer}>
      {alphabetButtons.map((letter, index) => (
        <AlphabetButton key={index} letter={letter} />
      ))}
    </View>
  );
};

const styles = StyleSheet.create({
  buttonContainer: {
    columnGap: 10,
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    gridColumnGap: 10,
    gridGap: 10,
    gridRowGap: 10,
    justifyContent: "center",
    marginBottom: 20,
    rowGap: 10,
    flexDirection: "row",
  },
});

export default AlphabetButtons;
